### ISSUE TITLE
Problem after uninstall add-on

### ISSUE THREAD

**Issue by Hydci** [homewayio/AddOn#29]
Hello,
I post the problem after uninstalling the addon I remain with this error after reboots do you have a solution?
Enregistreur: homeassistant.config_entries
Source: config_entries.py:604
S'est produit pour la première fois: 7 septembre 2024 à 10:06:27 (1 occurrences)
Dernier enregistrement: 7 septembre 2024 à 10:06:27

Error setting up entry homewayio for google_assistant
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/google_assistant/__init__.py", line 121, in async_setup_entry
    config: ConfigType = {**hass.data[DOMAIN][DATA_CONFIG]}
                            ~~~~~~~~~^^^^^^^^
KeyError: 'google_assistant'

**Comment by QuinnDamerell** [comment]
Hey! Thanks for letting me know! Can you send me a support ticket so you can share you home assistant config?

httpsl//homeway.io/support
